// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.onemena.game.proto;

/**
 * <pre>
 *公共头
 * </pre>
 *
 * Protobuf type {@code CommonProtocol}
 */
public  final class CommonProtocol extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CommonProtocol)
    CommonProtocolOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommonProtocol.newBuilder() to construct.
  private CommonProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommonProtocol() {
    data_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommonProtocol(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.onemena.game.proto.CommonProtocol.CommonHeader.Builder subBuilder = null;
            if (commHeader_ != null) {
              subBuilder = commHeader_.toBuilder();
            }
            commHeader_ = input.readMessage(com.onemena.game.proto.CommonProtocol.CommonHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(commHeader_);
              commHeader_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.onemena.game.proto.CommonProtocol.LiveCommonHeader.Builder subBuilder = null;
            if (liveHeader_ != null) {
              subBuilder = liveHeader_.toBuilder();
            }
            liveHeader_ = input.readMessage(com.onemena.game.proto.CommonProtocol.LiveCommonHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(liveHeader_);
              liveHeader_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {

            data_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.onemena.game.proto.Messages.internal_static_CommonProtocol_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.onemena.game.proto.Messages.internal_static_CommonProtocol_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.onemena.game.proto.CommonProtocol.class, com.onemena.game.proto.CommonProtocol.Builder.class);
  }

  public interface CommonHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommonProtocol.CommonHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 CommandId = 1;</code>
     */
    int getCommandId();

    /**
     * <code>uint32 SeqId = 2;</code>
     */
    int getSeqId();

    /**
     * <code>uint32 Version = 3;</code>
     */
    int getVersion();

    /**
     * <code>string FromUid = 4;</code>
     */
    java.lang.String getFromUid();
    /**
     * <code>string FromUid = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromUidBytes();
  }
  /**
   * Protobuf type {@code CommonProtocol.CommonHeader}
   */
  public  static final class CommonHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommonProtocol.CommonHeader)
      CommonHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommonHeader.newBuilder() to construct.
    private CommonHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommonHeader() {
      commandId_ = 0;
      seqId_ = 0;
      version_ = 0;
      fromUid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommonHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              commandId_ = input.readUInt32();
              break;
            }
            case 16: {

              seqId_ = input.readUInt32();
              break;
            }
            case 24: {

              version_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              fromUid_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.onemena.game.proto.Messages.internal_static_CommonProtocol_CommonHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.onemena.game.proto.Messages.internal_static_CommonProtocol_CommonHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.onemena.game.proto.CommonProtocol.CommonHeader.class, com.onemena.game.proto.CommonProtocol.CommonHeader.Builder.class);
    }

    public static final int COMMANDID_FIELD_NUMBER = 1;
    private int commandId_;
    /**
     * <code>uint32 CommandId = 1;</code>
     */
    public int getCommandId() {
      return commandId_;
    }

    public static final int SEQID_FIELD_NUMBER = 2;
    private int seqId_;
    /**
     * <code>uint32 SeqId = 2;</code>
     */
    public int getSeqId() {
      return seqId_;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private int version_;
    /**
     * <code>uint32 Version = 3;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int FROMUID_FIELD_NUMBER = 4;
    private volatile java.lang.Object fromUid_;
    /**
     * <code>string FromUid = 4;</code>
     */
    public java.lang.String getFromUid() {
      java.lang.Object ref = fromUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromUid_ = s;
        return s;
      }
    }
    /**
     * <code>string FromUid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromUidBytes() {
      java.lang.Object ref = fromUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commandId_ != 0) {
        output.writeUInt32(1, commandId_);
      }
      if (seqId_ != 0) {
        output.writeUInt32(2, seqId_);
      }
      if (version_ != 0) {
        output.writeUInt32(3, version_);
      }
      if (!getFromUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromUid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commandId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, commandId_);
      }
      if (seqId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, seqId_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, version_);
      }
      if (!getFromUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromUid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.onemena.game.proto.CommonProtocol.CommonHeader)) {
        return super.equals(obj);
      }
      com.onemena.game.proto.CommonProtocol.CommonHeader other = (com.onemena.game.proto.CommonProtocol.CommonHeader) obj;

      boolean result = true;
      result = result && (getCommandId()
          == other.getCommandId());
      result = result && (getSeqId()
          == other.getSeqId());
      result = result && (getVersion()
          == other.getVersion());
      result = result && getFromUid()
          .equals(other.getFromUid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMANDID_FIELD_NUMBER;
      hash = (53 * hash) + getCommandId();
      hash = (37 * hash) + SEQID_FIELD_NUMBER;
      hash = (53 * hash) + getSeqId();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + FROMUID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.onemena.game.proto.CommonProtocol.CommonHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.onemena.game.proto.CommonProtocol.CommonHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommonProtocol.CommonHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommonProtocol.CommonHeader)
        com.onemena.game.proto.CommonProtocol.CommonHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.onemena.game.proto.Messages.internal_static_CommonProtocol_CommonHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.onemena.game.proto.Messages.internal_static_CommonProtocol_CommonHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.onemena.game.proto.CommonProtocol.CommonHeader.class, com.onemena.game.proto.CommonProtocol.CommonHeader.Builder.class);
      }

      // Construct using com.onemena.game.proto.CommonProtocol.CommonHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        commandId_ = 0;

        seqId_ = 0;

        version_ = 0;

        fromUid_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.onemena.game.proto.Messages.internal_static_CommonProtocol_CommonHeader_descriptor;
      }

      @java.lang.Override
      public com.onemena.game.proto.CommonProtocol.CommonHeader getDefaultInstanceForType() {
        return com.onemena.game.proto.CommonProtocol.CommonHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.onemena.game.proto.CommonProtocol.CommonHeader build() {
        com.onemena.game.proto.CommonProtocol.CommonHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.onemena.game.proto.CommonProtocol.CommonHeader buildPartial() {
        com.onemena.game.proto.CommonProtocol.CommonHeader result = new com.onemena.game.proto.CommonProtocol.CommonHeader(this);
        result.commandId_ = commandId_;
        result.seqId_ = seqId_;
        result.version_ = version_;
        result.fromUid_ = fromUid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.onemena.game.proto.CommonProtocol.CommonHeader) {
          return mergeFrom((com.onemena.game.proto.CommonProtocol.CommonHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.onemena.game.proto.CommonProtocol.CommonHeader other) {
        if (other == com.onemena.game.proto.CommonProtocol.CommonHeader.getDefaultInstance()) return this;
        if (other.getCommandId() != 0) {
          setCommandId(other.getCommandId());
        }
        if (other.getSeqId() != 0) {
          setSeqId(other.getSeqId());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getFromUid().isEmpty()) {
          fromUid_ = other.fromUid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.onemena.game.proto.CommonProtocol.CommonHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.onemena.game.proto.CommonProtocol.CommonHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int commandId_ ;
      /**
       * <code>uint32 CommandId = 1;</code>
       */
      public int getCommandId() {
        return commandId_;
      }
      /**
       * <code>uint32 CommandId = 1;</code>
       */
      public Builder setCommandId(int value) {
        
        commandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 CommandId = 1;</code>
       */
      public Builder clearCommandId() {
        
        commandId_ = 0;
        onChanged();
        return this;
      }

      private int seqId_ ;
      /**
       * <code>uint32 SeqId = 2;</code>
       */
      public int getSeqId() {
        return seqId_;
      }
      /**
       * <code>uint32 SeqId = 2;</code>
       */
      public Builder setSeqId(int value) {
        
        seqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 SeqId = 2;</code>
       */
      public Builder clearSeqId() {
        
        seqId_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>uint32 Version = 3;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>uint32 Version = 3;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 Version = 3;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fromUid_ = "";
      /**
       * <code>string FromUid = 4;</code>
       */
      public java.lang.String getFromUid() {
        java.lang.Object ref = fromUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string FromUid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromUidBytes() {
        java.lang.Object ref = fromUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string FromUid = 4;</code>
       */
      public Builder setFromUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string FromUid = 4;</code>
       */
      public Builder clearFromUid() {
        
        fromUid_ = getDefaultInstance().getFromUid();
        onChanged();
        return this;
      }
      /**
       * <code>string FromUid = 4;</code>
       */
      public Builder setFromUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromUid_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommonProtocol.CommonHeader)
    }

    // @@protoc_insertion_point(class_scope:CommonProtocol.CommonHeader)
    private static final com.onemena.game.proto.CommonProtocol.CommonHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.onemena.game.proto.CommonProtocol.CommonHeader();
    }

    public static com.onemena.game.proto.CommonProtocol.CommonHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommonHeader>
        PARSER = new com.google.protobuf.AbstractParser<CommonHeader>() {
      @java.lang.Override
      public CommonHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommonHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommonHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.onemena.game.proto.CommonProtocol.CommonHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LiveCommonHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommonProtocol.LiveCommonHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 LiveType = 1;</code>
     */
    int getLiveType();

    /**
     * <code>uint32 LiveId = 2;</code>
     */
    int getLiveId();

    /**
     * <code>uint32 DemandType = 3;</code>
     */
    int getDemandType();

    /**
     * <code>uint32 DemandId = 4;</code>
     */
    int getDemandId();

    /**
     * <code>uint32 ToDemandId = 5;</code>
     */
    int getToDemandId();

    /**
     * <code>uint32 ToDemandType = 6;</code>
     */
    int getToDemandType();
  }
  /**
   * Protobuf type {@code CommonProtocol.LiveCommonHeader}
   */
  public  static final class LiveCommonHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommonProtocol.LiveCommonHeader)
      LiveCommonHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LiveCommonHeader.newBuilder() to construct.
    private LiveCommonHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LiveCommonHeader() {
      liveType_ = 0;
      liveId_ = 0;
      demandType_ = 0;
      demandId_ = 0;
      toDemandId_ = 0;
      toDemandType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LiveCommonHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              liveType_ = input.readUInt32();
              break;
            }
            case 16: {

              liveId_ = input.readUInt32();
              break;
            }
            case 24: {

              demandType_ = input.readUInt32();
              break;
            }
            case 32: {

              demandId_ = input.readUInt32();
              break;
            }
            case 40: {

              toDemandId_ = input.readUInt32();
              break;
            }
            case 48: {

              toDemandType_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.onemena.game.proto.Messages.internal_static_CommonProtocol_LiveCommonHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.onemena.game.proto.Messages.internal_static_CommonProtocol_LiveCommonHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.onemena.game.proto.CommonProtocol.LiveCommonHeader.class, com.onemena.game.proto.CommonProtocol.LiveCommonHeader.Builder.class);
    }

    public static final int LIVETYPE_FIELD_NUMBER = 1;
    private int liveType_;
    /**
     * <code>uint32 LiveType = 1;</code>
     */
    public int getLiveType() {
      return liveType_;
    }

    public static final int LIVEID_FIELD_NUMBER = 2;
    private int liveId_;
    /**
     * <code>uint32 LiveId = 2;</code>
     */
    public int getLiveId() {
      return liveId_;
    }

    public static final int DEMANDTYPE_FIELD_NUMBER = 3;
    private int demandType_;
    /**
     * <code>uint32 DemandType = 3;</code>
     */
    public int getDemandType() {
      return demandType_;
    }

    public static final int DEMANDID_FIELD_NUMBER = 4;
    private int demandId_;
    /**
     * <code>uint32 DemandId = 4;</code>
     */
    public int getDemandId() {
      return demandId_;
    }

    public static final int TODEMANDID_FIELD_NUMBER = 5;
    private int toDemandId_;
    /**
     * <code>uint32 ToDemandId = 5;</code>
     */
    public int getToDemandId() {
      return toDemandId_;
    }

    public static final int TODEMANDTYPE_FIELD_NUMBER = 6;
    private int toDemandType_;
    /**
     * <code>uint32 ToDemandType = 6;</code>
     */
    public int getToDemandType() {
      return toDemandType_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (liveType_ != 0) {
        output.writeUInt32(1, liveType_);
      }
      if (liveId_ != 0) {
        output.writeUInt32(2, liveId_);
      }
      if (demandType_ != 0) {
        output.writeUInt32(3, demandType_);
      }
      if (demandId_ != 0) {
        output.writeUInt32(4, demandId_);
      }
      if (toDemandId_ != 0) {
        output.writeUInt32(5, toDemandId_);
      }
      if (toDemandType_ != 0) {
        output.writeUInt32(6, toDemandType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (liveType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, liveType_);
      }
      if (liveId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, liveId_);
      }
      if (demandType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, demandType_);
      }
      if (demandId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, demandId_);
      }
      if (toDemandId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, toDemandId_);
      }
      if (toDemandType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, toDemandType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.onemena.game.proto.CommonProtocol.LiveCommonHeader)) {
        return super.equals(obj);
      }
      com.onemena.game.proto.CommonProtocol.LiveCommonHeader other = (com.onemena.game.proto.CommonProtocol.LiveCommonHeader) obj;

      boolean result = true;
      result = result && (getLiveType()
          == other.getLiveType());
      result = result && (getLiveId()
          == other.getLiveId());
      result = result && (getDemandType()
          == other.getDemandType());
      result = result && (getDemandId()
          == other.getDemandId());
      result = result && (getToDemandId()
          == other.getToDemandId());
      result = result && (getToDemandType()
          == other.getToDemandType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LIVETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLiveType();
      hash = (37 * hash) + LIVEID_FIELD_NUMBER;
      hash = (53 * hash) + getLiveId();
      hash = (37 * hash) + DEMANDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDemandType();
      hash = (37 * hash) + DEMANDID_FIELD_NUMBER;
      hash = (53 * hash) + getDemandId();
      hash = (37 * hash) + TODEMANDID_FIELD_NUMBER;
      hash = (53 * hash) + getToDemandId();
      hash = (37 * hash) + TODEMANDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getToDemandType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.onemena.game.proto.CommonProtocol.LiveCommonHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommonProtocol.LiveCommonHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommonProtocol.LiveCommonHeader)
        com.onemena.game.proto.CommonProtocol.LiveCommonHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.onemena.game.proto.Messages.internal_static_CommonProtocol_LiveCommonHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.onemena.game.proto.Messages.internal_static_CommonProtocol_LiveCommonHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.onemena.game.proto.CommonProtocol.LiveCommonHeader.class, com.onemena.game.proto.CommonProtocol.LiveCommonHeader.Builder.class);
      }

      // Construct using com.onemena.game.proto.CommonProtocol.LiveCommonHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        liveType_ = 0;

        liveId_ = 0;

        demandType_ = 0;

        demandId_ = 0;

        toDemandId_ = 0;

        toDemandType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.onemena.game.proto.Messages.internal_static_CommonProtocol_LiveCommonHeader_descriptor;
      }

      @java.lang.Override
      public com.onemena.game.proto.CommonProtocol.LiveCommonHeader getDefaultInstanceForType() {
        return com.onemena.game.proto.CommonProtocol.LiveCommonHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.onemena.game.proto.CommonProtocol.LiveCommonHeader build() {
        com.onemena.game.proto.CommonProtocol.LiveCommonHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.onemena.game.proto.CommonProtocol.LiveCommonHeader buildPartial() {
        com.onemena.game.proto.CommonProtocol.LiveCommonHeader result = new com.onemena.game.proto.CommonProtocol.LiveCommonHeader(this);
        result.liveType_ = liveType_;
        result.liveId_ = liveId_;
        result.demandType_ = demandType_;
        result.demandId_ = demandId_;
        result.toDemandId_ = toDemandId_;
        result.toDemandType_ = toDemandType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.onemena.game.proto.CommonProtocol.LiveCommonHeader) {
          return mergeFrom((com.onemena.game.proto.CommonProtocol.LiveCommonHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.onemena.game.proto.CommonProtocol.LiveCommonHeader other) {
        if (other == com.onemena.game.proto.CommonProtocol.LiveCommonHeader.getDefaultInstance()) return this;
        if (other.getLiveType() != 0) {
          setLiveType(other.getLiveType());
        }
        if (other.getLiveId() != 0) {
          setLiveId(other.getLiveId());
        }
        if (other.getDemandType() != 0) {
          setDemandType(other.getDemandType());
        }
        if (other.getDemandId() != 0) {
          setDemandId(other.getDemandId());
        }
        if (other.getToDemandId() != 0) {
          setToDemandId(other.getToDemandId());
        }
        if (other.getToDemandType() != 0) {
          setToDemandType(other.getToDemandType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.onemena.game.proto.CommonProtocol.LiveCommonHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.onemena.game.proto.CommonProtocol.LiveCommonHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int liveType_ ;
      /**
       * <code>uint32 LiveType = 1;</code>
       */
      public int getLiveType() {
        return liveType_;
      }
      /**
       * <code>uint32 LiveType = 1;</code>
       */
      public Builder setLiveType(int value) {
        
        liveType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 LiveType = 1;</code>
       */
      public Builder clearLiveType() {
        
        liveType_ = 0;
        onChanged();
        return this;
      }

      private int liveId_ ;
      /**
       * <code>uint32 LiveId = 2;</code>
       */
      public int getLiveId() {
        return liveId_;
      }
      /**
       * <code>uint32 LiveId = 2;</code>
       */
      public Builder setLiveId(int value) {
        
        liveId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 LiveId = 2;</code>
       */
      public Builder clearLiveId() {
        
        liveId_ = 0;
        onChanged();
        return this;
      }

      private int demandType_ ;
      /**
       * <code>uint32 DemandType = 3;</code>
       */
      public int getDemandType() {
        return demandType_;
      }
      /**
       * <code>uint32 DemandType = 3;</code>
       */
      public Builder setDemandType(int value) {
        
        demandType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 DemandType = 3;</code>
       */
      public Builder clearDemandType() {
        
        demandType_ = 0;
        onChanged();
        return this;
      }

      private int demandId_ ;
      /**
       * <code>uint32 DemandId = 4;</code>
       */
      public int getDemandId() {
        return demandId_;
      }
      /**
       * <code>uint32 DemandId = 4;</code>
       */
      public Builder setDemandId(int value) {
        
        demandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 DemandId = 4;</code>
       */
      public Builder clearDemandId() {
        
        demandId_ = 0;
        onChanged();
        return this;
      }

      private int toDemandId_ ;
      /**
       * <code>uint32 ToDemandId = 5;</code>
       */
      public int getToDemandId() {
        return toDemandId_;
      }
      /**
       * <code>uint32 ToDemandId = 5;</code>
       */
      public Builder setToDemandId(int value) {
        
        toDemandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 ToDemandId = 5;</code>
       */
      public Builder clearToDemandId() {
        
        toDemandId_ = 0;
        onChanged();
        return this;
      }

      private int toDemandType_ ;
      /**
       * <code>uint32 ToDemandType = 6;</code>
       */
      public int getToDemandType() {
        return toDemandType_;
      }
      /**
       * <code>uint32 ToDemandType = 6;</code>
       */
      public Builder setToDemandType(int value) {
        
        toDemandType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 ToDemandType = 6;</code>
       */
      public Builder clearToDemandType() {
        
        toDemandType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommonProtocol.LiveCommonHeader)
    }

    // @@protoc_insertion_point(class_scope:CommonProtocol.LiveCommonHeader)
    private static final com.onemena.game.proto.CommonProtocol.LiveCommonHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.onemena.game.proto.CommonProtocol.LiveCommonHeader();
    }

    public static com.onemena.game.proto.CommonProtocol.LiveCommonHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LiveCommonHeader>
        PARSER = new com.google.protobuf.AbstractParser<LiveCommonHeader>() {
      @java.lang.Override
      public LiveCommonHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LiveCommonHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LiveCommonHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LiveCommonHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.onemena.game.proto.CommonProtocol.LiveCommonHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int COMMHEADER_FIELD_NUMBER = 1;
  private com.onemena.game.proto.CommonProtocol.CommonHeader commHeader_;
  /**
   * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
   */
  public boolean hasCommHeader() {
    return commHeader_ != null;
  }
  /**
   * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
   */
  public com.onemena.game.proto.CommonProtocol.CommonHeader getCommHeader() {
    return commHeader_ == null ? com.onemena.game.proto.CommonProtocol.CommonHeader.getDefaultInstance() : commHeader_;
  }
  /**
   * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
   */
  public com.onemena.game.proto.CommonProtocol.CommonHeaderOrBuilder getCommHeaderOrBuilder() {
    return getCommHeader();
  }

  public static final int LIVEHEADER_FIELD_NUMBER = 2;
  private com.onemena.game.proto.CommonProtocol.LiveCommonHeader liveHeader_;
  /**
   * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
   */
  public boolean hasLiveHeader() {
    return liveHeader_ != null;
  }
  /**
   * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
   */
  public com.onemena.game.proto.CommonProtocol.LiveCommonHeader getLiveHeader() {
    return liveHeader_ == null ? com.onemena.game.proto.CommonProtocol.LiveCommonHeader.getDefaultInstance() : liveHeader_;
  }
  /**
   * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
   */
  public com.onemena.game.proto.CommonProtocol.LiveCommonHeaderOrBuilder getLiveHeaderOrBuilder() {
    return getLiveHeader();
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes Data = 3;</code>
   */
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (commHeader_ != null) {
      output.writeMessage(1, getCommHeader());
    }
    if (liveHeader_ != null) {
      output.writeMessage(2, getLiveHeader());
    }
    if (!data_.isEmpty()) {
      output.writeBytes(3, data_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (commHeader_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCommHeader());
    }
    if (liveHeader_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLiveHeader());
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.onemena.game.proto.CommonProtocol)) {
      return super.equals(obj);
    }
    com.onemena.game.proto.CommonProtocol other = (com.onemena.game.proto.CommonProtocol) obj;

    boolean result = true;
    result = result && (hasCommHeader() == other.hasCommHeader());
    if (hasCommHeader()) {
      result = result && getCommHeader()
          .equals(other.getCommHeader());
    }
    result = result && (hasLiveHeader() == other.hasLiveHeader());
    if (hasLiveHeader()) {
      result = result && getLiveHeader()
          .equals(other.getLiveHeader());
    }
    result = result && getData()
        .equals(other.getData());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCommHeader()) {
      hash = (37 * hash) + COMMHEADER_FIELD_NUMBER;
      hash = (53 * hash) + getCommHeader().hashCode();
    }
    if (hasLiveHeader()) {
      hash = (37 * hash) + LIVEHEADER_FIELD_NUMBER;
      hash = (53 * hash) + getLiveHeader().hashCode();
    }
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.onemena.game.proto.CommonProtocol parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.onemena.game.proto.CommonProtocol parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.onemena.game.proto.CommonProtocol parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.onemena.game.proto.CommonProtocol parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.onemena.game.proto.CommonProtocol parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.onemena.game.proto.CommonProtocol parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.onemena.game.proto.CommonProtocol parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.onemena.game.proto.CommonProtocol parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.onemena.game.proto.CommonProtocol parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.onemena.game.proto.CommonProtocol parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.onemena.game.proto.CommonProtocol parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.onemena.game.proto.CommonProtocol parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.onemena.game.proto.CommonProtocol prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *公共头
   * </pre>
   *
   * Protobuf type {@code CommonProtocol}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CommonProtocol)
      com.onemena.game.proto.CommonProtocolOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.onemena.game.proto.Messages.internal_static_CommonProtocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.onemena.game.proto.Messages.internal_static_CommonProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.onemena.game.proto.CommonProtocol.class, com.onemena.game.proto.CommonProtocol.Builder.class);
    }

    // Construct using com.onemena.game.proto.CommonProtocol.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (commHeaderBuilder_ == null) {
        commHeader_ = null;
      } else {
        commHeader_ = null;
        commHeaderBuilder_ = null;
      }
      if (liveHeaderBuilder_ == null) {
        liveHeader_ = null;
      } else {
        liveHeader_ = null;
        liveHeaderBuilder_ = null;
      }
      data_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.onemena.game.proto.Messages.internal_static_CommonProtocol_descriptor;
    }

    @java.lang.Override
    public com.onemena.game.proto.CommonProtocol getDefaultInstanceForType() {
      return com.onemena.game.proto.CommonProtocol.getDefaultInstance();
    }

    @java.lang.Override
    public com.onemena.game.proto.CommonProtocol build() {
      com.onemena.game.proto.CommonProtocol result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.onemena.game.proto.CommonProtocol buildPartial() {
      com.onemena.game.proto.CommonProtocol result = new com.onemena.game.proto.CommonProtocol(this);
      if (commHeaderBuilder_ == null) {
        result.commHeader_ = commHeader_;
      } else {
        result.commHeader_ = commHeaderBuilder_.build();
      }
      if (liveHeaderBuilder_ == null) {
        result.liveHeader_ = liveHeader_;
      } else {
        result.liveHeader_ = liveHeaderBuilder_.build();
      }
      result.data_ = data_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.onemena.game.proto.CommonProtocol) {
        return mergeFrom((com.onemena.game.proto.CommonProtocol)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.onemena.game.proto.CommonProtocol other) {
      if (other == com.onemena.game.proto.CommonProtocol.getDefaultInstance()) return this;
      if (other.hasCommHeader()) {
        mergeCommHeader(other.getCommHeader());
      }
      if (other.hasLiveHeader()) {
        mergeLiveHeader(other.getLiveHeader());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.onemena.game.proto.CommonProtocol parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.onemena.game.proto.CommonProtocol) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.onemena.game.proto.CommonProtocol.CommonHeader commHeader_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.onemena.game.proto.CommonProtocol.CommonHeader, com.onemena.game.proto.CommonProtocol.CommonHeader.Builder, com.onemena.game.proto.CommonProtocol.CommonHeaderOrBuilder> commHeaderBuilder_;
    /**
     * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    public boolean hasCommHeader() {
      return commHeaderBuilder_ != null || commHeader_ != null;
    }
    /**
     * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    public com.onemena.game.proto.CommonProtocol.CommonHeader getCommHeader() {
      if (commHeaderBuilder_ == null) {
        return commHeader_ == null ? com.onemena.game.proto.CommonProtocol.CommonHeader.getDefaultInstance() : commHeader_;
      } else {
        return commHeaderBuilder_.getMessage();
      }
    }
    /**
     * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    public Builder setCommHeader(com.onemena.game.proto.CommonProtocol.CommonHeader value) {
      if (commHeaderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        commHeader_ = value;
        onChanged();
      } else {
        commHeaderBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    public Builder setCommHeader(
        com.onemena.game.proto.CommonProtocol.CommonHeader.Builder builderForValue) {
      if (commHeaderBuilder_ == null) {
        commHeader_ = builderForValue.build();
        onChanged();
      } else {
        commHeaderBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    public Builder mergeCommHeader(com.onemena.game.proto.CommonProtocol.CommonHeader value) {
      if (commHeaderBuilder_ == null) {
        if (commHeader_ != null) {
          commHeader_ =
            com.onemena.game.proto.CommonProtocol.CommonHeader.newBuilder(commHeader_).mergeFrom(value).buildPartial();
        } else {
          commHeader_ = value;
        }
        onChanged();
      } else {
        commHeaderBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    public Builder clearCommHeader() {
      if (commHeaderBuilder_ == null) {
        commHeader_ = null;
        onChanged();
      } else {
        commHeader_ = null;
        commHeaderBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    public com.onemena.game.proto.CommonProtocol.CommonHeader.Builder getCommHeaderBuilder() {
      
      onChanged();
      return getCommHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    public com.onemena.game.proto.CommonProtocol.CommonHeaderOrBuilder getCommHeaderOrBuilder() {
      if (commHeaderBuilder_ != null) {
        return commHeaderBuilder_.getMessageOrBuilder();
      } else {
        return commHeader_ == null ?
            com.onemena.game.proto.CommonProtocol.CommonHeader.getDefaultInstance() : commHeader_;
      }
    }
    /**
     * <code>.CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.onemena.game.proto.CommonProtocol.CommonHeader, com.onemena.game.proto.CommonProtocol.CommonHeader.Builder, com.onemena.game.proto.CommonProtocol.CommonHeaderOrBuilder> 
        getCommHeaderFieldBuilder() {
      if (commHeaderBuilder_ == null) {
        commHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.onemena.game.proto.CommonProtocol.CommonHeader, com.onemena.game.proto.CommonProtocol.CommonHeader.Builder, com.onemena.game.proto.CommonProtocol.CommonHeaderOrBuilder>(
                getCommHeader(),
                getParentForChildren(),
                isClean());
        commHeader_ = null;
      }
      return commHeaderBuilder_;
    }

    private com.onemena.game.proto.CommonProtocol.LiveCommonHeader liveHeader_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.onemena.game.proto.CommonProtocol.LiveCommonHeader, com.onemena.game.proto.CommonProtocol.LiveCommonHeader.Builder, com.onemena.game.proto.CommonProtocol.LiveCommonHeaderOrBuilder> liveHeaderBuilder_;
    /**
     * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    public boolean hasLiveHeader() {
      return liveHeaderBuilder_ != null || liveHeader_ != null;
    }
    /**
     * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    public com.onemena.game.proto.CommonProtocol.LiveCommonHeader getLiveHeader() {
      if (liveHeaderBuilder_ == null) {
        return liveHeader_ == null ? com.onemena.game.proto.CommonProtocol.LiveCommonHeader.getDefaultInstance() : liveHeader_;
      } else {
        return liveHeaderBuilder_.getMessage();
      }
    }
    /**
     * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    public Builder setLiveHeader(com.onemena.game.proto.CommonProtocol.LiveCommonHeader value) {
      if (liveHeaderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        liveHeader_ = value;
        onChanged();
      } else {
        liveHeaderBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    public Builder setLiveHeader(
        com.onemena.game.proto.CommonProtocol.LiveCommonHeader.Builder builderForValue) {
      if (liveHeaderBuilder_ == null) {
        liveHeader_ = builderForValue.build();
        onChanged();
      } else {
        liveHeaderBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    public Builder mergeLiveHeader(com.onemena.game.proto.CommonProtocol.LiveCommonHeader value) {
      if (liveHeaderBuilder_ == null) {
        if (liveHeader_ != null) {
          liveHeader_ =
            com.onemena.game.proto.CommonProtocol.LiveCommonHeader.newBuilder(liveHeader_).mergeFrom(value).buildPartial();
        } else {
          liveHeader_ = value;
        }
        onChanged();
      } else {
        liveHeaderBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    public Builder clearLiveHeader() {
      if (liveHeaderBuilder_ == null) {
        liveHeader_ = null;
        onChanged();
      } else {
        liveHeader_ = null;
        liveHeaderBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    public com.onemena.game.proto.CommonProtocol.LiveCommonHeader.Builder getLiveHeaderBuilder() {
      
      onChanged();
      return getLiveHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    public com.onemena.game.proto.CommonProtocol.LiveCommonHeaderOrBuilder getLiveHeaderOrBuilder() {
      if (liveHeaderBuilder_ != null) {
        return liveHeaderBuilder_.getMessageOrBuilder();
      } else {
        return liveHeader_ == null ?
            com.onemena.game.proto.CommonProtocol.LiveCommonHeader.getDefaultInstance() : liveHeader_;
      }
    }
    /**
     * <code>.CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.onemena.game.proto.CommonProtocol.LiveCommonHeader, com.onemena.game.proto.CommonProtocol.LiveCommonHeader.Builder, com.onemena.game.proto.CommonProtocol.LiveCommonHeaderOrBuilder> 
        getLiveHeaderFieldBuilder() {
      if (liveHeaderBuilder_ == null) {
        liveHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.onemena.game.proto.CommonProtocol.LiveCommonHeader, com.onemena.game.proto.CommonProtocol.LiveCommonHeader.Builder, com.onemena.game.proto.CommonProtocol.LiveCommonHeaderOrBuilder>(
                getLiveHeader(),
                getParentForChildren(),
                isClean());
        liveHeader_ = null;
      }
      return liveHeaderBuilder_;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes Data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes Data = 3;</code>
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes Data = 3;</code>
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CommonProtocol)
  }

  // @@protoc_insertion_point(class_scope:CommonProtocol)
  private static final com.onemena.game.proto.CommonProtocol DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.onemena.game.proto.CommonProtocol();
  }

  public static com.onemena.game.proto.CommonProtocol getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommonProtocol>
      PARSER = new com.google.protobuf.AbstractParser<CommonProtocol>() {
    @java.lang.Override
    public CommonProtocol parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommonProtocol(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommonProtocol> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommonProtocol> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.onemena.game.proto.CommonProtocol getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

