// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.onemena.game.proto;

public interface HeartBeatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartBeatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
